import VerticalBar from "@/components/VerticalBar";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import HorizontalChart from "@/components/HorizontalChart";
import PieChart from "@/components/PieChart/index copy";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <VerticalBar/>
        <HorizontalChart/>
        <PieChart className={styles.pie}style={{width:"200px", height:"200px"}}/>
      </main>
    </>
  );
}
